# Generated by Django 3.1 on 2020-08-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='api_token',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
